seafilemysql:
  image: library/mysql
  environment:
    MYSQL_ROOT_PASSWORD: supersecretmysqlpassword
seafile:
  image: cloudfleet/zeppelin-seafile
  links:
    - seafilemysql:db
  environment:
    DB_ROOT_PASSWORD: supersecretmysqlpassword
    DB_PASSWORD: seafile_password
    SERVER_DOMAIN: files.example.com
